Example of distance between different objects (MAP, MAS, MAT,...)

In [1]:
import numpy as np
import pandas
import matplotlib.pylab as pl

In [2]:
import sys
sys.path.append('../script/')
from distances import distance_aniso,distances_aniso,distances_aniso_along,distances_iso_aniso,distances_iso_aniso_along,distances_spatial_iso_aniso,distances_spatial_iso_aniso_along,distance_MAP,distances_MAP,distance_MAS,distance_MAS_idx,distances_MAS_idx,distance_MAT_idx
from utils import random_MASs,sqrtm,sqrtms

# Centroid MASs

In [3]:
d=3
k1,k2=4,5
nb_MAS1,nb_MAS2=10,11 #nb streamline
nb_MAP1,nb_MAP2=20,21 #nb points on streamline
m1,wI1,I1,w1,S1=random_MASs(nb_MAS1,nb_MAP1,k1,d)
m2,wI2,I2,w2,S2=random_MASs(nb_MAS2,nb_MAP2,k2,d)
print(m1.shape,wI1.shape,I1.shape,w1.shape,S1.shape)
print(m2.shape,wI2.shape,I2.shape,w2.shape,S2.shape)

(10, 20, 3) (10, 20) (10, 20) (10, 20, 4) (10, 20, 4, 3, 3)
(11, 21, 3) (11, 21) (11, 21) (11, 21, 5) (11, 21, 5, 3, 3)


In [4]:
# Distance between two covariates
print(distance_aniso(S1[0,0,0],S2[0,0,0]))

#matrix of distances between two covariates
print(distances_aniso(S1[0,0],S2[0,0]).shape)
print(distances_aniso(S1[0,0],S2[0,0])[0,0])

#matrices of distances between two covariates along a streamline
print(distances_aniso_along(S1[0],S2[0,:20]).shape)
print(distances_aniso_along(S1[0],S2[0,:20])[0,0,0])

0.10069574487318533
(4, 5)
0.10069574487318533
(20, 4, 5)
0.10069574487318533


In [5]:
#matrix of distances between two covariates and isotropic compartment
print(distances_iso_aniso(I1[0,0],I2[0,0],S1[0,0],S2[0,0]))

#matrix of distances between two covariates and isotropic compartment along a streamline
print(distances_iso_aniso_along(I1[0],I2[0,:20],S1[0],S2[0,:20])[0])
print(distances_iso_aniso_along(I1[0],I2[0,:20],S1[0],S2[0,:20]).shape)

[[ 0.48789494 11.45419904 10.75879901  7.69945063  6.69748753  5.80211838]
 [18.82681226  0.10069574  0.40101099  3.05869355  3.13228573  4.30937038]
 [ 1.83803219  8.26909394  7.96247443  4.85642663  4.72759514  3.10863495]
 [12.75878258  1.49482526  1.45701981  2.60422883  1.15056809  3.79174152]
 [ 5.87219749  3.59939834  3.30634115  3.39827262  1.75209677  2.69678233]]
[[ 0.48789494 11.45419904 10.75879901  7.69945063  6.69748753  5.80211838]
 [18.82681226  0.10069574  0.40101099  3.05869355  3.13228573  4.30937038]
 [ 1.83803219  8.26909394  7.96247443  4.85642663  4.72759514  3.10863495]
 [12.75878258  1.49482526  1.45701981  2.60422883  1.15056809  3.79174152]
 [ 5.87219749  3.59939834  3.30634115  3.39827262  1.75209677  2.69678233]]
(20, 5, 6)


In [6]:
#matrix of distances between two spatials, covariates and isotropic compartment
print(distances_spatial_iso_aniso(m1[0,0],m2[0,0],I1[0,0],I2[0,0],S1[0,0],S2[0,0]))
print(distances_spatial_iso_aniso(m1[0,0],m2[0,0],I1[0,0],I2[0,0],S1[0,0],S2[0,0]).shape)

#matrix of distances between two spatials, covariates and isotropic compartment along a streamline
print(distances_spatial_iso_aniso_along(m1[0],m2[0,:20],I1[0],I2[0,:20],S1[0],S2[0,:20])[0])
print(distances_spatial_iso_aniso_along(m1[0],m2[0,:20],I1[0],I2[0,:20],S1[0],S2[0,:20]).shape)

[[ 0.93525099  6.41840304  6.07070302  4.54102883  4.04004728  3.5923627 ]
 [10.10470965  0.74165139  0.89180901  2.22065029  2.25744638  2.84598871]
 [ 1.61031961  4.82585049  4.67254073  3.11951683  3.05510109  2.24562099]
 [ 7.07069481  1.43871615  1.41981342  1.99341793  1.26658756  2.58717427]
 [ 3.62740226  2.49100269  2.34447409  2.39043982  1.5673519   2.03969468]]
(5, 6)
[[ 0.93525099  6.41840304  6.07070302  4.54102883  4.04004728  3.5923627 ]
 [10.10470965  0.74165139  0.89180901  2.22065029  2.25744638  2.84598871]
 [ 1.61031961  4.82585049  4.67254073  3.11951683  3.05510109  2.24562099]
 [ 7.07069481  1.43871615  1.41981342  1.99341793  1.26658756  2.58717427]
 [ 3.62740226  2.49100269  2.34447409  2.39043982  1.5673519   2.03969468]]
(20, 5, 6)


In [7]:
# distance between 2 MAPs 
print(distance_MAP(m1[0,0],m2[0,0],wI1[0,0],wI2[0,0],I1[0,0],I2[0,0],w1[0,0],w2[0,0],S1[0,0],S2[0,0],alpha=.5))

# Matrix of distance between 2 MAPs 
print(distances_MAP(m1[0],m2[0],wI1[0],wI2[0],I1[0],I2[0],w1[0],w2[0],S1[0],S2[0],alpha=.5).shape)
print(distances_MAP(m1[0],m2[0],wI1[0],wI2[0],I1[0],I2[0],w1[0],w2[0],S1[0],S2[0],alpha=.5)[0])

1.785263925923075
(20, 21)
[1.78526393 2.45996193 2.62714091 3.75497115 1.55679474 1.93546429
 2.25615382 2.08536652 0.96364056 2.22663575 3.31195995 1.48459953
 1.55537365 2.08266643 1.75188164 1.23559235 5.66221265 3.93311721
 4.6184375  1.49183973 2.24000997]


In [8]:
#Distance between 2 MAS (with aligned indices)
print(distance_MAS_idx(m1[0],m2[0,:20],wI1[0],wI2[0,:20],I1[0],I2[0,:20],w1[0],w2[0,:20],S1[0],S2[0,:20],alpha=.5))

#Distance between 2 MAS
print(distance_MAS(m1[0],m2[0],wI1[0],wI2[0],I1[0],I2[0],w1[0],w2[0],S1[0],S2[0],alpha=.5))

#Matrix of distance between MAS
print(distances_MAS_idx(m1,m2[:,:20],wI1,wI2[:,:20],I1,I2[:,:20],w1,w2[:,:20],S1,S2[:,:20],alpha=0.5).shape)

4.1239282411192795
1.8088981523967802
(10, 11)


In [9]:
#Distance between 2 similar tracts
print(distance_MAT_idx(m1,m1,wI1,wI1,I1,I1,w1,w1,S1,S1,alpha=.5,reflexion=False,lam1=0,lam2=0))


#Distance between 2 tracts
print(distance_MAT_idx(m1,m2[:10,:20],wI1,wI2[:10,:20],I1,I2[:10,:20],w1,w2[:10,:20],S1,S2[:10,:20],alpha=.5,reflexion=False,lam1=0,lam2=0))

0 3.425727077457392e-14
0 1 37.40079682207375
